# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-11 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_granja', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('precipitacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altitud', models.DecimalField(decimal_places=2, max_digits=6)),
                ('zona_vida', models.CharField(max_length=50)),
                ('humedad_relativa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temp_prom', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
