# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-11 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granja',
            name='temp_prom',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
