# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-11 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0002_auto_20160911_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='granja',
            name='mapa',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
