# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Granja', '0005_auto_20161005_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granja',
            name='altitud',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Altitud (m)'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='humedad_relativa',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='H\xfamedad relativa (%)'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='id_departamento',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_granja_departamento', to='Departamento.Departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='id_estado',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_granja_estado', to='EstadoGranja.EstadoGranja', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='id_municipio',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_granja_municipio', to='Municipio.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='precipitacion',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precipitaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='temp_prom',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura promedio (\xb0C)'),
        ),
        migrations.AlterField(
            model_name='granja',
            name='zona_vida',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_granja_zonavida', to='ZonaVida.ZonaVida', verbose_name='Zona de vida'),
        ),
    ]
