# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(max_length=50)),
                ('id_granja', models.CharField(max_length=50)),
                ('aforo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
