# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='id_potrero',
            field=models.CharField(default='', max_length=50),
        ),
    ]
