# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrero', '0002_potrero_id_potrero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potrero',
            name='id_potrero',
            field=models.CharField(max_length=50),
        ),
    ]
