# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0004_auto_20160912_0439'),
        ('potrero', '0003_auto_20160912_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granja_Potrero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granja.Granja')),
                ('potrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potrero.Potrero')),
            ],
            options={
                'verbose_name': 'Pertenece a',
            },
        ),
    ]
