# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SemenToro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sementoro',
            name='id_semen_toro',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
