# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-06 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bovino', '0006_auto_20161006_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bovino',
            name='fechaSalida',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='fecha_primer_servicio',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Fecha de primer servicio'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='motivo_salida',
            field=models.TextField(blank=True, default=None, max_length=140),
        ),
    ]
