# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-06 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bovino', '0008_auto_20161006_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bovino',
            name='edad_primer_parto',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Edad del primer parto'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='fechaSalida',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='fecha_destete',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de destete'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='fecha_primer_servicio',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de primer servicio'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='motivo_salida',
            field=models.TextField(blank=True, default=None, max_length=140, null=True),
        ),
    ]
