# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bovino', '0009_auto_20161006_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bovino',
            name='id_bovino',
            field=models.CharField(max_length=140, primary_key=True, serialize=False, verbose_name='Identificaci\xf3n del bovino'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_estado',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='EstadoBovino.EstadoBovino', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_etapa',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Etapa.Etapa', verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_granja',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Granja.Granja', verbose_name='Granja a la que pertenece'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_madre',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_madre_bovino', to='Bovino.Bovino', verbose_name='Identificaci\xf3n del bovino madre'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_padre',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_padre_bovino', to='Bovino.Bovino', verbose_name='Identificaci\xf3n del bovino padre'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_parto',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='TipoParto.TipoParto', verbose_name='Tipo parto'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_procedencia',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Procedencia.Procedencia', verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_raza',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Raza.Raza', verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='id_sexo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Sexo.Sexo', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='motivo_salida',
            field=models.TextField(blank=True, default=None, max_length=140, null=True, verbose_name='Motivo de salida'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='nombre',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre'),
        ),
    ]
