# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstadoReproduccion', '0001_initial'),
        ('Reproduccion', '0002_auto_20161003_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduccion',
            name='cantCelosPosParto',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='reproduccion',
            name='id_estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_estado', to='EstadoReproduccion.EstadoReproduccion'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='fechaPosibleParto',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='fechaSecado',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_cria',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_cria', to='Bovino.Bovino'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_semen_toro',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_semen', to='SemenToro.SemenToro'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_servicio', to='Servicio.Servicio'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_toro',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_toro', to='Bovino.Bovino'),
        ),
    ]
