# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0003_auto_20161007_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduccion',
            name='cantCelosPosParto',
            field=models.IntegerField(blank=True, default=None, verbose_name='Cantidad de celos posparto'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='fechaPosibleParto',
            field=models.DateTimeField(blank=True, verbose_name='Fecha del posible parto'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='fechaSecado',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de secado'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='fecha_servicio',
            field=models.DateTimeField(verbose_name='Fecha del servicio'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_bovino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_bovino', to='Bovino.Bovino', verbose_name='Idenficaci\xf3n del bovino'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_cria',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_cria', to='Bovino.Bovino', verbose_name='Idenficaci\xf3n de la cr\xeda'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_estado', to='EstadoReproduccion.EstadoReproduccion', to_field='nombre', verbose_name='Estado de la reproducci\xf3n'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_semen_toro',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_semen', to='SemenToro.SemenToro', verbose_name='Idenficaci\xf3n del semen del toro'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_servicio', to='Servicio.Servicio', verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_toro',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_toro', to='Bovino.Bovino', verbose_name='Idenficaci\xf3n del toro'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='proximoCelo',
            field=models.DateTimeField(verbose_name='Idenficaci\xf3n del pr\xf3ximo celo'),
        ),
    ]
