# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0004_auto_20161007_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduccion',
            name='id_estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_estado', to='EstadoReproduccion.EstadoReproduccion', verbose_name='Estado de la reproducci\xf3n'),
        ),
    ]
