# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reproduccion', '0005_auto_20161007_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduccion',
            name='cantCelosPosParto',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Cantidad de celos posparto'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='fechaPosibleParto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del posible parto'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='fechaSecado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de secado'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_cria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_cria', to='Bovino.Bovino', verbose_name='Idenficaci\xf3n de la cr\xeda'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_semen_toro',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_semen', to='SemenToro.SemenToro', verbose_name='Idenficaci\xf3n del semen del toro'),
        ),
        migrations.AlterField(
            model_name='reproduccion',
            name='id_toro',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_toro', to='Bovino.Bovino', verbose_name='Idenficaci\xf3n del toro'),
        ),
    ]
